LOAD '/home/blizhan/repo/github/duckomo/build/grid-matrix/baseline-1.5.4/builds/15f751c1929b88adebbfe2a150a8c7987f92de29af7fc0b806a6af1cd80388c8/release/extension/duckomo/duckomo.duckdb_extension';
SET threads=1;
SET duckomo_max_threads=1;
SET duckomo_cache_enabled=true;
SET duckomo_cache_capacity=67108864;

CREATE TEMP TABLE work_small AS SELECT "gaussian_work/value" AS value FROM read_om('/home/blizhan/repo/github/duckomo/test/data/grids/gaussian-work-small.om', dimensions := map(['gaussian_work/value'], [['point']]), grid := {'version':1,'type':'reduced_gaussian','numeric_policy':'float64_v1','earth':{'model':'wgs84','semi_major_m':6378137.0,'inverse_flattening':298.257223563},'layout':{'order':'row_major'},'parameters':{'n':1,'latitude_rule':'explicit_v1','rows':[{'latitude': 60.0, 'point_count': 128, 'longitude_origin': 0.0, 'longitude_step': 1.0}, {'latitude': -60.0, 'point_count': 128, 'longitude_origin': 0.0, 'longitude_step': 1.0}],'subset_segments':NULL}}, spatial_axes := ['point']) WHERE latitude = 60 AND longitude BETWEEN 0 AND 2;

COPY (SELECT (SELECT count(*)::UBIGINT FROM work_small) AS result_rows, (SELECT sum(value)::DOUBLE FROM work_small) AS result_sum, (SELECT min(value)::DOUBLE FROM work_small) AS result_min, (SELECT max(value)::DOUBLE FROM work_small) AS result_max, metrics::JSON AS metrics FROM duckomo_last_scan_metrics() ORDER BY scan_id DESC LIMIT 1) TO '/home/blizhan/repo/github/duckomo/specs/004-multi-grid-selection/evidence/baseline-local/h5-local-refresh-20261008-core-functions/us2-local/work-peak-reduced_gaussian/small.json' (FORMAT JSON, ARRAY false);

CREATE TEMP TABLE work_large AS SELECT "gaussian_work/value" AS value FROM read_om('/home/blizhan/repo/github/duckomo/test/data/grids/gaussian-work-large.om', dimensions := map(['gaussian_work/value'], [['point']]), grid := {'version':1,'type':'reduced_gaussian','numeric_policy':'float64_v1','earth':{'model':'wgs84','semi_major_m':6378137.0,'inverse_flattening':298.257223563},'layout':{'order':'row_major'},'parameters':{'n':8,'latitude_rule':'explicit_v1','rows':[{'latitude': 90.0, 'point_count': 256, 'longitude_origin': 0.0, 'longitude_step': 1.0}, {'latitude': 80.0, 'point_count': 256, 'longitude_origin': 0.0, 'longitude_step': 1.0}, {'latitude': 70.0, 'point_count': 256, 'longitude_origin': 0.0, 'longitude_step': 1.0}, {'latitude': 60.0, 'point_count': 128, 'longitude_origin': 0.0, 'longitude_step': 1.0}, {'latitude': 50.0, 'point_count': 256, 'longitude_origin': 0.0, 'longitude_step': 1.0}, {'latitude': 40.0, 'point_count': 256, 'longitude_origin': 0.0, 'longitude_step': 1.0}, {'latitude': 30.0, 'point_count': 256, 'longitude_origin': 0.0, 'longitude_step': 1.0}, {'latitude': 20.0, 'point_count': 256, 'longitude_origin': 0.0, 'longitude_step': 1.0}, {'latitude': 10.0, 'point_count': 256, 'longitude_origin': 0.0, 'longitude_step': 1.0}, {'latitude': 0.0, 'point_count': 256, 'longitude_origin': 0.0, 'longitude_step': 1.0}, {'latitude': -10.0, 'point_count': 256, 'longitude_origin': 0.0, 'longitude_step': 1.0}, {'latitude': -20.0, 'point_count': 256, 'longitude_origin': 0.0, 'longitude_step': 1.0}, {'latitude': -30.0, 'point_count': 256, 'longitude_origin': 0.0, 'longitude_step': 1.0}, {'latitude': -40.0, 'point_count': 256, 'longitude_origin': 0.0, 'longitude_step': 1.0}, {'latitude': -60.0, 'point_count': 256, 'longitude_origin': 0.0, 'longitude_step': 1.0}, {'latitude': -90.0, 'point_count': 256, 'longitude_origin': 0.0, 'longitude_step': 1.0}],'subset_segments':NULL}}, spatial_axes := ['point']) WHERE latitude = 60 AND longitude BETWEEN 0 AND 2;

COPY (SELECT (SELECT count(*)::UBIGINT FROM work_large) AS result_rows, (SELECT sum(value)::DOUBLE FROM work_large) AS result_sum, (SELECT min(value)::DOUBLE FROM work_large) AS result_min, (SELECT max(value)::DOUBLE FROM work_large) AS result_max, metrics::JSON AS metrics FROM duckomo_last_scan_metrics() ORDER BY scan_id DESC LIMIT 1) TO '/home/blizhan/repo/github/duckomo/specs/004-multi-grid-selection/evidence/baseline-local/h5-local-refresh-20261008-core-functions/us2-local/work-peak-reduced_gaussian/large.json' (FORMAT JSON, ARRAY false);

