-- Generated by scripts/generate-grid-registry.py; do not edit.
-- Inputs are pinned by test/data/grids/sample-manifest.json and definitions.json.
-- sample-manifest sha256: 72af60d4769c2fc7b262864f1fb8e4f434e8a89ec463824f482c39103dc1939f
-- definitions sha256: 225caadf963c6f584850180f0e3c948cdbcebbf25a2a0d39aaef184b005f7da0
-- This file contains executable samples only where the manifest has a compatible object/fixture.
-- Synthetic fixtures are labelled and cannot establish producer coordinate/value support.
-- The O1280 ECMWF HRES objects are real OM v3, but have no verified N-grid identity or point order.
SET threads = 1;

-- gem_rdps_10km: rotated_cmc_gem_rdps_10km_cape_chunk_4337; explicit and domain forms use the same frozen input.
CREATE TEMP VIEW explicit_gem_rdps_10km AS
SELECT * FROM read_om(
    'build/s3-samples/openmeteo-v3/cmc-gem-rdps-10km-cape-chunk-4337.om',
    dimensions := map(['value'], [[
    'y',
    'x',
    'time'
]]),
    grid := {
            'version': 1,
            'type': 'rotated_latlon',
            'numeric_policy': 'openmeteo_f32_v1',
            'earth': {
                'model': 'sphere',
                'radius_m': 6371229.0
            },
            'layout': {
                'nx': 1140,
                'ny': 1045,
                'order': 'separate'
            },
            'parameters': {
                'x0': -53.859,
                'y0': -48.806,
                'dx': 0.090298,
                'dy': 0.090298,
                'north_pole_latitude': 31.7583,
                'north_pole_longitude': 87.597,
                'rotation': 180
            }
        },
    spatial_axes := ['y', 'x'],
    include_source := true
);
CREATE TEMP VIEW domain_gem_rdps_10km AS
SELECT * FROM read_om(
    'build/s3-samples/openmeteo-v3/cmc-gem-rdps-10km-cape-chunk-4337.om',
    dimensions := map(['value'], [[
    'y',
    'x',
    'time'
]]),
    domain := 'gem_rdps_10km',
    include_source := true
);
CREATE TEMP TABLE baseline_gem_rdps_10km AS SELECT * FROM explicit_gem_rdps_10km;
-- Full input was materialized before any restricted query for gem_rdps_10km.
SELECT count(*) AS full_rows_gem_rdps_10km FROM explicit_gem_rdps_10km;
SELECT count(*) AS materialized_rows_gem_rdps_10km FROM baseline_gem_rdps_10km;
SELECT count(*) AS domain_identity_difference_gem_rdps_10km FROM (
    (SELECT om_source.grid_id, om_source.layout_id FROM explicit_gem_rdps_10km
     EXCEPT ALL SELECT om_source.grid_id, om_source.layout_id FROM domain_gem_rdps_10km)
    UNION ALL
    (SELECT om_source.grid_id, om_source.layout_id FROM domain_gem_rdps_10km
     EXCEPT ALL SELECT om_source.grid_id, om_source.layout_id FROM explicit_gem_rdps_10km)
);
SELECT count(*) AS restricted_difference_gem_rdps_10km FROM (
    (SELECT * FROM baseline_gem_rdps_10km WHERE latitude BETWEEN -10 AND 10 AND longitude BETWEEN -10 AND 10
     EXCEPT ALL SELECT * FROM explicit_gem_rdps_10km WHERE latitude BETWEEN -10 AND 10 AND longitude BETWEEN -10 AND 10)
    UNION ALL
    (SELECT * FROM explicit_gem_rdps_10km WHERE latitude BETWEEN -10 AND 10 AND longitude BETWEEN -10 AND 10
     EXCEPT ALL SELECT * FROM baseline_gem_rdps_10km WHERE latitude BETWEEN -10 AND 10 AND longitude BETWEEN -10 AND 10)
);
SELECT count(*) AS seam_rows_gem_rdps_10km FROM explicit_gem_rdps_10km WHERE 
    (longitude BETWEEN 170 AND 180 OR longitude BETWEEN -180 AND -170);
SELECT count(*) AS empty_rows_gem_rdps_10km FROM explicit_gem_rdps_10km WHERE latitude > 90;
SELECT count(*) AS fallback_rows_gem_rdps_10km FROM explicit_gem_rdps_10km WHERE abs(latitude) < 1;
SELECT om_source.logical_index, longitude, latitude,
       (longitude BETWEEN -1 AND 1 AND latitude BETWEEN -1 AND 1) AS polygon_covers_point
FROM explicit_gem_rdps_10km -- POLYGON((-1 -1, 1 -1, 1 1, -1 1, -1 -1)), lon/lat order
WHERE longitude BETWEEN -1 AND 1 AND latitude BETWEEN -1 AND 1 LIMIT 64;

-- gem_regional: stereographic_cmc_gem_rdps_cape_chunk_4337; explicit and domain forms use the same frozen input.
CREATE TEMP VIEW explicit_gem_regional AS
SELECT * FROM read_om(
    'build/s3-samples/openmeteo-v3/cmc-gem-rdps-cape-chunk-4337.om',
    dimensions := map(['value'], [[
    'y',
    'x',
    'time'
]]),
    grid := {
            'version': 1,
            'type': 'stereographic',
            'numeric_policy': 'openmeteo_f32_v1',
            'earth': {
                'model': 'sphere',
                'radius_m': 6371229.0
            },
            'layout': {
                'nx': 935,
                'ny': 824,
                'order': 'separate'
            },
            'parameters': {
                'x0': -4878222.0,
                'y0': -7839461.0,
                'dx': 10717.9697265625,
                'dy': 10717.9658203125,
                'central_meridian': 249.0,
                'latitude_of_origin': 90.0,
                'scale_factor': 1.0
            }
        },
    spatial_axes := ['y', 'x'],
    include_source := true
);
CREATE TEMP VIEW domain_gem_regional AS
SELECT * FROM read_om(
    'build/s3-samples/openmeteo-v3/cmc-gem-rdps-cape-chunk-4337.om',
    dimensions := map(['value'], [[
    'y',
    'x',
    'time'
]]),
    domain := 'gem_regional',
    include_source := true
);
CREATE TEMP TABLE baseline_gem_regional AS SELECT * FROM explicit_gem_regional;
-- Full input was materialized before any restricted query for gem_regional.
SELECT count(*) AS full_rows_gem_regional FROM explicit_gem_regional;
SELECT count(*) AS materialized_rows_gem_regional FROM baseline_gem_regional;
SELECT count(*) AS domain_identity_difference_gem_regional FROM (
    (SELECT om_source.grid_id, om_source.layout_id FROM explicit_gem_regional
     EXCEPT ALL SELECT om_source.grid_id, om_source.layout_id FROM domain_gem_regional)
    UNION ALL
    (SELECT om_source.grid_id, om_source.layout_id FROM domain_gem_regional
     EXCEPT ALL SELECT om_source.grid_id, om_source.layout_id FROM explicit_gem_regional)
);
SELECT count(*) AS restricted_difference_gem_regional FROM (
    (SELECT * FROM baseline_gem_regional WHERE latitude BETWEEN -10 AND 10 AND longitude BETWEEN -10 AND 10
     EXCEPT ALL SELECT * FROM explicit_gem_regional WHERE latitude BETWEEN -10 AND 10 AND longitude BETWEEN -10 AND 10)
    UNION ALL
    (SELECT * FROM explicit_gem_regional WHERE latitude BETWEEN -10 AND 10 AND longitude BETWEEN -10 AND 10
     EXCEPT ALL SELECT * FROM baseline_gem_regional WHERE latitude BETWEEN -10 AND 10 AND longitude BETWEEN -10 AND 10)
);
SELECT count(*) AS seam_rows_gem_regional FROM explicit_gem_regional WHERE 
    (longitude BETWEEN 170 AND 180 OR longitude BETWEEN -180 AND -170);
SELECT count(*) AS empty_rows_gem_regional FROM explicit_gem_regional WHERE latitude > 90;
SELECT count(*) AS fallback_rows_gem_regional FROM explicit_gem_regional WHERE abs(latitude) < 1;
SELECT om_source.logical_index, longitude, latitude,
       (longitude BETWEEN -1 AND 1 AND latitude BETWEEN -1 AND 1) AS polygon_covers_point
FROM explicit_gem_regional -- POLYGON((-1 -1, 1 -1, 1 1, -1 1, -1 -1)), lon/lat order
WHERE longitude BETWEEN -1 AND 1 AND latitude BETWEEN -1 AND 1 LIMIT 64;

-- aladin_central_europe_2km: lambert_chmi_aladin_central_europe_2km_cape_chunk_4135; explicit and domain forms use the same frozen input.
CREATE TEMP VIEW explicit_aladin_central_europe_2km AS
SELECT * FROM read_om(
    'build/s3-samples/openmeteo-v3/chmi-aladin-ce-cape-chunk-4135.om',
    dimensions := map(['value'], [[
    'y',
    'x',
    'time'
]]),
    grid := {
            'version': 1,
            'type': 'lambert_conformal_conic',
            'numeric_policy': 'openmeteo_f32_v1',
            'earth': {
                'model': 'sphere',
                'radius_m': 6371229.0
            },
            'layout': {
                'nx': 1053,
                'ny': 837,
                'order': 'separate'
            },
            'parameters': {
                'x0': -1364242.5,
                'y0': -717413.5,
                'dx': 2325.0,
                'dy': 2325.0,
                'central_meridian': 17.0,
                'latitude_of_origin': 46.244,
                'standard_parallel_1': 46.244,
                'standard_parallel_2': 46.244
            }
        },
    spatial_axes := ['y', 'x'],
    include_source := true
);
CREATE TEMP VIEW domain_aladin_central_europe_2km AS
SELECT * FROM read_om(
    'build/s3-samples/openmeteo-v3/chmi-aladin-ce-cape-chunk-4135.om',
    dimensions := map(['value'], [[
    'y',
    'x',
    'time'
]]),
    domain := 'aladin_central_europe_2km',
    include_source := true
);
CREATE TEMP TABLE baseline_aladin_central_europe_2km AS SELECT * FROM explicit_aladin_central_europe_2km;
-- Full input was materialized before any restricted query for aladin_central_europe_2km.
SELECT count(*) AS full_rows_aladin_central_europe_2km FROM explicit_aladin_central_europe_2km;
SELECT count(*) AS materialized_rows_aladin_central_europe_2km FROM baseline_aladin_central_europe_2km;
SELECT count(*) AS domain_identity_difference_aladin_central_europe_2km FROM (
    (SELECT om_source.grid_id, om_source.layout_id FROM explicit_aladin_central_europe_2km
     EXCEPT ALL SELECT om_source.grid_id, om_source.layout_id FROM domain_aladin_central_europe_2km)
    UNION ALL
    (SELECT om_source.grid_id, om_source.layout_id FROM domain_aladin_central_europe_2km
     EXCEPT ALL SELECT om_source.grid_id, om_source.layout_id FROM explicit_aladin_central_europe_2km)
);
SELECT count(*) AS restricted_difference_aladin_central_europe_2km FROM (
    (SELECT * FROM baseline_aladin_central_europe_2km WHERE latitude BETWEEN -10 AND 10 AND longitude BETWEEN -10 AND 10
     EXCEPT ALL SELECT * FROM explicit_aladin_central_europe_2km WHERE latitude BETWEEN -10 AND 10 AND longitude BETWEEN -10 AND 10)
    UNION ALL
    (SELECT * FROM explicit_aladin_central_europe_2km WHERE latitude BETWEEN -10 AND 10 AND longitude BETWEEN -10 AND 10
     EXCEPT ALL SELECT * FROM baseline_aladin_central_europe_2km WHERE latitude BETWEEN -10 AND 10 AND longitude BETWEEN -10 AND 10)
);
SELECT count(*) AS seam_rows_aladin_central_europe_2km FROM explicit_aladin_central_europe_2km WHERE 
    (longitude BETWEEN 170 AND 180 OR longitude BETWEEN -180 AND -170);
SELECT count(*) AS empty_rows_aladin_central_europe_2km FROM explicit_aladin_central_europe_2km WHERE latitude > 90;
SELECT count(*) AS fallback_rows_aladin_central_europe_2km FROM explicit_aladin_central_europe_2km WHERE abs(latitude) < 1;
SELECT om_source.logical_index, longitude, latitude,
       (longitude BETWEEN -1 AND 1 AND latitude BETWEEN -1 AND 1) AS polygon_covers_point
FROM explicit_aladin_central_europe_2km -- POLYGON((-1 -1, 1 -1, 1 1, -1 1, -1 -1)), lon/lat order
WHERE longitude BETWEEN -1 AND 1 AND latitude BETWEEN -1 AND 1 LIMIT 64;

-- n160: gaussian_n160_identity (synthetic identity only); explicit and domain forms use the same frozen input.
CREATE TEMP VIEW explicit_n160 AS
SELECT * FROM read_om(
    'test/data/grids/gaussian-n160-identity.om',
    dimensions := map(['n160_identity/value'], [[
    'point'
]]),
    grid := {
            'version': 1,
            'type': 'reduced_gaussian',
            'numeric_policy': 'openmeteo_f32_v1',
            'earth': {
                'model': 'wgs84',
                'semi_major_m': 6378137.0,
                'inverse_flattening': 298.257223563
            },
            'layout': {
                'order': 'row_major'
            },
            'parameters': {
                'n': 160,
                'latitude_rule': 'openmeteo_approx_v1',
                'rows': [
                    {
                        'latitude': 89.57877349853516,
                        'point_count': 18,
                        'longitude_origin': 0.0,
                        'longitude_step': 20.0
                    },
                    {
                        'latitude': 89.01715087890625,
                        'point_count': 25,
                        'longitude_origin': 0.0,
                        'longitude_step': 14.399999618530273
                    },
                    {
                        'latitude': 88.45552825927734,
                        'point_count': 36,
                        'longitude_origin': 0.0,
                        'longitude_step': 10.0
                    },
                    {
                        'latitude': 87.89390563964844,
                        'point_count': 40,
                        'longitude_origin': 0.0,
                        'longitude_step': 9.0
                    },
                    {
                        'latitude': 87.33228302001953,
                        'point_count': 45,
                        'longitude_origin': 0.0,
                        'longitude_step': 8.0
                    },
                    {
                        'latitude': 86.77066040039062,
                        'point_count': 50,
                        'longitude_origin': 0.0,
                        'longitude_step': 7.199999809265137
                    },
                    {
                        'latitude': 86.20903778076172,
                        'point_count': 60,
                        'longitude_origin': 0.0,
                        'longitude_step': 6.0
                    },
                    {
                        'latitude': 85.64741516113281,
                        'point_count': 64,
                        'longitude_origin': 0.0,
                        'longitude_step': 5.625
                    },
                    {
                        'latitude': 85.0857925415039,
                        'point_count': 72,
                        'longitude_origin': 0.0,
                        'longitude_step': 5.0
                    },
                    {
                        'latitude': 84.524169921875,
                        'point_count': 72,
                        'longitude_origin': 0.0,
                        'longitude_step': 5.0
                    },
                    {
                        'latitude': 83.96255493164062,
                        'point_count': 80,
                        'longitude_origin': 0.0,
                        'longitude_step': 4.5
                    },
                    {
                        'latitude': 83.40093231201172,
                        'point_count': 90,
                        'longitude_origin': 0.0,
                        'longitude_step': 4.0
                    },
                    {
                        'latitude': 82.83930969238281,
                        'point_count': 90,
                        'longitude_origin': 0.0,
                        'longitude_step': 4.0
                    },
                    {
                        'latitude': 82.2776870727539,
                        'point_count': 96,
                        'longitude_origin': 0.0,
                        'longitude_step': 3.75
                    },
                    {
                        'latitude': 81.716064453125,
                        'point_count': 108,
                        'longitude_origin': 0.0,
                        'longitude_step': 3.3333332538604736
                    },
                    {
                        'latitude': 81.1544418334961,
                        'point_count': 120,
                        'longitude_origin': 0.0,
                        'longitude_step': 3.0
                    },
                    {
                        'latitude': 80.59281921386719,
                        'point_count': 120,
                        'longitude_origin': 0.0,
                        'longitude_step': 3.0
                    },
                    {
                        'latitude': 80.03119659423828,
                        'point_count': 125,
                        'longitude_origin': 0.0,
                        'longitude_step': 2.880000114440918
                    },
                    {
                        'latitude': 79.46957397460938,
                        'point_count': 128,
                        'longitude_origin': 0.0,
                        'longitude_step': 2.8125
                    },
                    {
                        'latitude': 78.90795135498047,
                        'point_count': 135,
                        'longitude_origin': 0.0,
                        'longitude_step': 2.6666667461395264
                    },
                    {
                        'latitude': 78.34632873535156,
                        'point_count': 144,
                        'longitude_origin': 0.0,
                        'longitude_step': 2.5
                    },
                    {
                        'latitude': 77.78470611572266,
                        'point_count': 150,
                        'longitude_origin': 0.0,
                        'longitude_step': 2.4000000953674316
                    },
                    {
                        'latitude': 77.22308349609375,
                        'point_count': 160,
                        'longitude_origin': 0.0,
                        'longitude_step': 2.25
                    },
                    {
                        'latitude': 76.66146087646484,
                        'point_count': 160,
                        'longitude_origin': 0.0,
                        'longitude_step': 2.25
                    },
                    {
                        'latitude': 76.09983825683594,
                        'point_count': 180,
                        'longitude_origin': 0.0,
                        'longitude_step': 2.0
                    },
                    {
                        'latitude': 75.53821563720703,
                        'point_count': 180,
                        'longitude_origin': 0.0,
                        'longitude_step': 2.0
                    },
                    {
                        'latitude': 74.97659301757812,
                        'point_count': 180,
                        'longitude_origin': 0.0,
                        'longitude_step': 2.0
                    },
                    {
                        'latitude': 74.41497039794922,
                        'point_count': 192,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.875
                    },
                    {
                        'latitude': 73.85334777832031,
                        'point_count': 192,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.875
                    },
                    {
                        'latitude': 73.2917251586914,
                        'point_count': 200,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.7999999523162842
                    },
                    {
                        'latitude': 72.7301025390625,
                        'point_count': 216,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.6666666269302368
                    },
                    {
                        'latitude': 72.1684799194336,
                        'point_count': 216,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.6666666269302368
                    },
                    {
                        'latitude': 71.60685729980469,
                        'point_count': 225,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.600000023841858
                    },
                    {
                        'latitude': 71.04523468017578,
                        'point_count': 225,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.600000023841858
                    },
                    {
                        'latitude': 70.48361206054688,
                        'point_count': 240,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.5
                    },
                    {
                        'latitude': 69.92198944091797,
                        'point_count': 240,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.5
                    },
                    {
                        'latitude': 69.36036682128906,
                        'point_count': 243,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.4814814329147339
                    },
                    {
                        'latitude': 68.79874420166016,
                        'point_count': 250,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.440000057220459
                    },
                    {
                        'latitude': 68.23712158203125,
                        'point_count': 256,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.40625
                    },
                    {
                        'latitude': 67.67549896240234,
                        'point_count': 270,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.3333333730697632
                    },
                    {
                        'latitude': 67.11387634277344,
                        'point_count': 270,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.3333333730697632
                    },
                    {
                        'latitude': 66.55225372314453,
                        'point_count': 288,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.25
                    },
                    {
                        'latitude': 65.99063110351562,
                        'point_count': 288,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.25
                    },
                    {
                        'latitude': 65.42900848388672,
                        'point_count': 288,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.25
                    },
                    {
                        'latitude': 64.86738586425781,
                        'point_count': 300,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.2000000476837158
                    },
                    {
                        'latitude': 64.3057632446289,
                        'point_count': 300,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.2000000476837158
                    },
                    {
                        'latitude': 63.74414825439453,
                        'point_count': 320,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.125
                    },
                    {
                        'latitude': 63.182525634765625,
                        'point_count': 320,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.125
                    },
                    {
                        'latitude': 62.62090301513672,
                        'point_count': 320,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.125
                    },
                    {
                        'latitude': 62.05928039550781,
                        'point_count': 320,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.125
                    },
                    {
                        'latitude': 61.497657775878906,
                        'point_count': 324,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.1111111640930176
                    },
                    {
                        'latitude': 60.93603515625,
                        'point_count': 360,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.0
                    },
                    {
                        'latitude': 60.374412536621094,
                        'point_count': 360,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.0
                    },
                    {
                        'latitude': 59.81278991699219,
                        'point_count': 360,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.0
                    },
                    {
                        'latitude': 59.25116729736328,
                        'point_count': 360,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.0
                    },
                    {
                        'latitude': 58.689544677734375,
                        'point_count': 360,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.0
                    },
                    {
                        'latitude': 58.12792205810547,
                        'point_count': 360,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.0
                    },
                    {
                        'latitude': 57.56629943847656,
                        'point_count': 375,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.9599999785423279
                    },
                    {
                        'latitude': 57.004676818847656,
                        'point_count': 375,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.9599999785423279
                    },
                    {
                        'latitude': 56.44305419921875,
                        'point_count': 375,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.9599999785423279
                    },
                    {
                        'latitude': 55.881431579589844,
                        'point_count': 384,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.9375
                    },
                    {
                        'latitude': 55.31980895996094,
                        'point_count': 384,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.9375
                    },
                    {
                        'latitude': 54.75818634033203,
                        'point_count': 400,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.8999999761581421
                    },
                    {
                        'latitude': 54.19656753540039,
                        'point_count': 400,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.8999999761581421
                    },
                    {
                        'latitude': 53.634944915771484,
                        'point_count': 400,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.8999999761581421
                    },
                    {
                        'latitude': 53.07332229614258,
                        'point_count': 405,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.8888888955116272
                    },
                    {
                        'latitude': 52.51169967651367,
                        'point_count': 432,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.8333333134651184
                    },
                    {
                        'latitude': 51.950077056884766,
                        'point_count': 432,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.8333333134651184
                    },
                    {
                        'latitude': 51.38845443725586,
                        'point_count': 432,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.8333333134651184
                    },
                    {
                        'latitude': 50.82683181762695,
                        'point_count': 432,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.8333333134651184
                    },
                    {
                        'latitude': 50.26520919799805,
                        'point_count': 432,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.8333333134651184
                    },
                    {
                        'latitude': 49.70358657836914,
                        'point_count': 450,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.800000011920929
                    },
                    {
                        'latitude': 49.141963958740234,
                        'point_count': 450,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.800000011920929
                    },
                    {
                        'latitude': 48.58034133911133,
                        'point_count': 450,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.800000011920929
                    },
                    {
                        'latitude': 48.01871871948242,
                        'point_count': 450,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.800000011920929
                    },
                    {
                        'latitude': 47.457096099853516,
                        'point_count': 480,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.75
                    },
                    {
                        'latitude': 46.89547348022461,
                        'point_count': 480,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.75
                    },
                    {
                        'latitude': 46.3338508605957,
                        'point_count': 480,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.75
                    },
                    {
                        'latitude': 45.7722282409668,
                        'point_count': 480,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.75
                    },
                    {
                        'latitude': 45.21060562133789,
                        'point_count': 480,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.75
                    },
                    {
                        'latitude': 44.648983001708984,
                        'point_count': 480,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.75
                    },
                    {
                        'latitude': 44.08736038208008,
                        'point_count': 480,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.75
                    },
                    {
                        'latitude': 43.52573776245117,
                        'point_count': 500,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.7200000286102295
                    },
                    {
                        'latitude': 42.964115142822266,
                        'point_count': 500,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.7200000286102295
                    },
                    {
                        'latitude': 42.40249252319336,
                        'point_count': 500,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.7200000286102295
                    },
                    {
                        'latitude': 41.84087371826172,
                        'point_count': 500,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.7200000286102295
                    },
                    {
                        'latitude': 41.27925109863281,
                        'point_count': 500,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.7200000286102295
                    },
                    {
                        'latitude': 40.717628479003906,
                        'point_count': 512,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.703125
                    },
                    {
                        'latitude': 40.156005859375,
                        'point_count': 512,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.703125
                    },
                    {
                        'latitude': 39.594383239746094,
                        'point_count': 540,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6666666865348816
                    },
                    {
                        'latitude': 39.03276062011719,
                        'point_count': 540,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6666666865348816
                    },
                    {
                        'latitude': 38.47113800048828,
                        'point_count': 540,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6666666865348816
                    },
                    {
                        'latitude': 37.909515380859375,
                        'point_count': 540,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6666666865348816
                    },
                    {
                        'latitude': 37.34789276123047,
                        'point_count': 540,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6666666865348816
                    },
                    {
                        'latitude': 36.78627014160156,
                        'point_count': 540,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6666666865348816
                    },
                    {
                        'latitude': 36.224647521972656,
                        'point_count': 540,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6666666865348816
                    },
                    {
                        'latitude': 35.66302490234375,
                        'point_count': 540,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6666666865348816
                    },
                    {
                        'latitude': 35.101402282714844,
                        'point_count': 576,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.625
                    },
                    {
                        'latitude': 34.53977966308594,
                        'point_count': 576,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.625
                    },
                    {
                        'latitude': 33.97815704345703,
                        'point_count': 576,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.625
                    },
                    {
                        'latitude': 33.416534423828125,
                        'point_count': 576,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.625
                    },
                    {
                        'latitude': 32.85491180419922,
                        'point_count': 576,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.625
                    },
                    {
                        'latitude': 32.29328918457031,
                        'point_count': 576,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.625
                    },
                    {
                        'latitude': 31.73166847229004,
                        'point_count': 576,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.625
                    },
                    {
                        'latitude': 31.170045852661133,
                        'point_count': 576,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.625
                    },
                    {
                        'latitude': 30.608423233032227,
                        'point_count': 576,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.625
                    },
                    {
                        'latitude': 30.04680061340332,
                        'point_count': 576,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.625
                    },
                    {
                        'latitude': 29.485177993774414,
                        'point_count': 600,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6000000238418579
                    },
                    {
                        'latitude': 28.923555374145508,
                        'point_count': 600,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6000000238418579
                    },
                    {
                        'latitude': 28.3619327545166,
                        'point_count': 600,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6000000238418579
                    },
                    {
                        'latitude': 27.800310134887695,
                        'point_count': 600,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6000000238418579
                    },
                    {
                        'latitude': 27.238689422607422,
                        'point_count': 600,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6000000238418579
                    },
                    {
                        'latitude': 26.677066802978516,
                        'point_count': 600,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6000000238418579
                    },
                    {
                        'latitude': 26.11544418334961,
                        'point_count': 600,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6000000238418579
                    },
                    {
                        'latitude': 25.553821563720703,
                        'point_count': 600,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6000000238418579
                    },
                    {
                        'latitude': 24.992198944091797,
                        'point_count': 600,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6000000238418579
                    },
                    {
                        'latitude': 24.43057632446289,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 23.868953704833984,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 23.307331085205078,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 22.745708465576172,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 22.184085845947266,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 21.62246322631836,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 21.060842514038086,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 20.49921989440918,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 19.937597274780273,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 19.375974655151367,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 18.81435203552246,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 18.252729415893555,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 17.69110679626465,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 17.129484176635742,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 16.567861557006836,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 16.00623893737793,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 15.44461727142334,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 14.882994651794434,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 14.321372032165527,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 13.759750366210938,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 13.198127746582031,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 12.636505126953125,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 12.074882507324219,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 11.513259887695312,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 10.951637268066406,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 10.390015602111816,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 9.82839298248291,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 9.266770362854004,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 8.705147743225098,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 8.143525123596191,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 7.581902980804443,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 7.020280838012695,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 6.458658218383789,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 5.897035598754883,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 5.335413455963135,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 4.7737908363342285,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 4.212168216705322,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 3.650546073913574,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 3.088923454284668,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 2.527301073074341,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 1.9656785726547241,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 1.4040560722351074,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 0.8424336910247803,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': 0.28081122040748596,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -0.28081122040748596,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -0.8424336910247803,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -1.404056191444397,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -1.9656785726547241,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -2.5273008346557617,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -3.088923454284668,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -3.650545835494995,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -4.212168216705322,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -4.7737908363342285,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -5.335412979125977,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -5.897035598754883,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -6.458658218383789,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -7.020280361175537,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -7.581902980804443,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -8.143525123596191,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -8.705147743225098,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -9.266770362854004,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -9.82839298248291,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -10.3900146484375,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -10.951637268066406,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -11.513259887695312,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -12.074882507324219,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -12.636505126953125,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -13.198127746582031,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -13.759749412536621,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -14.321372032165527,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -14.882994651794434,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -15.44461727142334,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -16.00623893737793,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -16.567861557006836,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -17.129484176635742,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -17.69110679626465,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -18.252729415893555,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -18.81435203552246,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -19.375974655151367,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -19.937597274780273,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -20.49921989440918,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -21.060840606689453,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -21.62246322631836,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -22.184085845947266,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -22.745708465576172,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -23.307331085205078,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -23.868953704833984,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -24.43057632446289,
                        'point_count': 640,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.5625
                    },
                    {
                        'latitude': -24.992198944091797,
                        'point_count': 600,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6000000238418579
                    },
                    {
                        'latitude': -25.553821563720703,
                        'point_count': 600,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6000000238418579
                    },
                    {
                        'latitude': -26.11544418334961,
                        'point_count': 600,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6000000238418579
                    },
                    {
                        'latitude': -26.677066802978516,
                        'point_count': 600,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6000000238418579
                    },
                    {
                        'latitude': -27.23868751525879,
                        'point_count': 600,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6000000238418579
                    },
                    {
                        'latitude': -27.800310134887695,
                        'point_count': 600,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6000000238418579
                    },
                    {
                        'latitude': -28.3619327545166,
                        'point_count': 600,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6000000238418579
                    },
                    {
                        'latitude': -28.923555374145508,
                        'point_count': 600,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6000000238418579
                    },
                    {
                        'latitude': -29.485177993774414,
                        'point_count': 600,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6000000238418579
                    },
                    {
                        'latitude': -30.04680061340332,
                        'point_count': 576,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.625
                    },
                    {
                        'latitude': -30.608423233032227,
                        'point_count': 576,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.625
                    },
                    {
                        'latitude': -31.170045852661133,
                        'point_count': 576,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.625
                    },
                    {
                        'latitude': -31.731666564941406,
                        'point_count': 576,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.625
                    },
                    {
                        'latitude': -32.29328918457031,
                        'point_count': 576,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.625
                    },
                    {
                        'latitude': -32.85491180419922,
                        'point_count': 576,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.625
                    },
                    {
                        'latitude': -33.416534423828125,
                        'point_count': 576,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.625
                    },
                    {
                        'latitude': -33.97815704345703,
                        'point_count': 576,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.625
                    },
                    {
                        'latitude': -34.53977966308594,
                        'point_count': 576,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.625
                    },
                    {
                        'latitude': -35.101402282714844,
                        'point_count': 576,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.625
                    },
                    {
                        'latitude': -35.66302490234375,
                        'point_count': 540,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6666666865348816
                    },
                    {
                        'latitude': -36.224647521972656,
                        'point_count': 540,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6666666865348816
                    },
                    {
                        'latitude': -36.78627014160156,
                        'point_count': 540,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6666666865348816
                    },
                    {
                        'latitude': -37.34789276123047,
                        'point_count': 540,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6666666865348816
                    },
                    {
                        'latitude': -37.909515380859375,
                        'point_count': 540,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6666666865348816
                    },
                    {
                        'latitude': -38.47113800048828,
                        'point_count': 540,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6666666865348816
                    },
                    {
                        'latitude': -39.03276062011719,
                        'point_count': 540,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6666666865348816
                    },
                    {
                        'latitude': -39.594383239746094,
                        'point_count': 540,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.6666666865348816
                    },
                    {
                        'latitude': -40.156005859375,
                        'point_count': 512,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.703125
                    },
                    {
                        'latitude': -40.717628479003906,
                        'point_count': 512,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.703125
                    },
                    {
                        'latitude': -41.27925109863281,
                        'point_count': 500,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.7200000286102295
                    },
                    {
                        'latitude': -41.84086990356445,
                        'point_count': 500,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.7200000286102295
                    },
                    {
                        'latitude': -42.40249252319336,
                        'point_count': 500,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.7200000286102295
                    },
                    {
                        'latitude': -42.964115142822266,
                        'point_count': 500,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.7200000286102295
                    },
                    {
                        'latitude': -43.52573776245117,
                        'point_count': 500,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.7200000286102295
                    },
                    {
                        'latitude': -44.08736038208008,
                        'point_count': 480,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.75
                    },
                    {
                        'latitude': -44.648983001708984,
                        'point_count': 480,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.75
                    },
                    {
                        'latitude': -45.21060562133789,
                        'point_count': 480,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.75
                    },
                    {
                        'latitude': -45.7722282409668,
                        'point_count': 480,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.75
                    },
                    {
                        'latitude': -46.3338508605957,
                        'point_count': 480,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.75
                    },
                    {
                        'latitude': -46.89547348022461,
                        'point_count': 480,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.75
                    },
                    {
                        'latitude': -47.457096099853516,
                        'point_count': 480,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.75
                    },
                    {
                        'latitude': -48.01871871948242,
                        'point_count': 450,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.800000011920929
                    },
                    {
                        'latitude': -48.58034133911133,
                        'point_count': 450,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.800000011920929
                    },
                    {
                        'latitude': -49.141963958740234,
                        'point_count': 450,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.800000011920929
                    },
                    {
                        'latitude': -49.70358657836914,
                        'point_count': 450,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.800000011920929
                    },
                    {
                        'latitude': -50.26520919799805,
                        'point_count': 432,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.8333333134651184
                    },
                    {
                        'latitude': -50.82683181762695,
                        'point_count': 432,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.8333333134651184
                    },
                    {
                        'latitude': -51.38845443725586,
                        'point_count': 432,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.8333333134651184
                    },
                    {
                        'latitude': -51.950077056884766,
                        'point_count': 432,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.8333333134651184
                    },
                    {
                        'latitude': -52.51169967651367,
                        'point_count': 432,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.8333333134651184
                    },
                    {
                        'latitude': -53.07332229614258,
                        'point_count': 405,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.8888888955116272
                    },
                    {
                        'latitude': -53.634944915771484,
                        'point_count': 400,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.8999999761581421
                    },
                    {
                        'latitude': -54.196563720703125,
                        'point_count': 400,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.8999999761581421
                    },
                    {
                        'latitude': -54.75818634033203,
                        'point_count': 400,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.8999999761581421
                    },
                    {
                        'latitude': -55.31980895996094,
                        'point_count': 384,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.9375
                    },
                    {
                        'latitude': -55.881431579589844,
                        'point_count': 384,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.9375
                    },
                    {
                        'latitude': -56.44305419921875,
                        'point_count': 375,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.9599999785423279
                    },
                    {
                        'latitude': -57.004676818847656,
                        'point_count': 375,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.9599999785423279
                    },
                    {
                        'latitude': -57.56629943847656,
                        'point_count': 375,
                        'longitude_origin': 0.0,
                        'longitude_step': 0.9599999785423279
                    },
                    {
                        'latitude': -58.12792205810547,
                        'point_count': 360,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.0
                    },
                    {
                        'latitude': -58.689544677734375,
                        'point_count': 360,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.0
                    },
                    {
                        'latitude': -59.25116729736328,
                        'point_count': 360,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.0
                    },
                    {
                        'latitude': -59.81278991699219,
                        'point_count': 360,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.0
                    },
                    {
                        'latitude': -60.374412536621094,
                        'point_count': 360,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.0
                    },
                    {
                        'latitude': -60.93603515625,
                        'point_count': 360,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.0
                    },
                    {
                        'latitude': -61.497657775878906,
                        'point_count': 324,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.1111111640930176
                    },
                    {
                        'latitude': -62.05928039550781,
                        'point_count': 320,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.125
                    },
                    {
                        'latitude': -62.62090301513672,
                        'point_count': 320,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.125
                    },
                    {
                        'latitude': -63.182525634765625,
                        'point_count': 320,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.125
                    },
                    {
                        'latitude': -63.744144439697266,
                        'point_count': 320,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.125
                    },
                    {
                        'latitude': -64.30577087402344,
                        'point_count': 300,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.2000000476837158
                    },
                    {
                        'latitude': -64.86739349365234,
                        'point_count': 300,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.2000000476837158
                    },
                    {
                        'latitude': -65.42901611328125,
                        'point_count': 288,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.25
                    },
                    {
                        'latitude': -65.99063873291016,
                        'point_count': 288,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.25
                    },
                    {
                        'latitude': -66.55226135253906,
                        'point_count': 288,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.25
                    },
                    {
                        'latitude': -67.11388397216797,
                        'point_count': 270,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.3333333730697632
                    },
                    {
                        'latitude': -67.67550659179688,
                        'point_count': 270,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.3333333730697632
                    },
                    {
                        'latitude': -68.23712921142578,
                        'point_count': 256,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.40625
                    },
                    {
                        'latitude': -68.79875183105469,
                        'point_count': 250,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.440000057220459
                    },
                    {
                        'latitude': -69.3603744506836,
                        'point_count': 243,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.4814814329147339
                    },
                    {
                        'latitude': -69.9219970703125,
                        'point_count': 240,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.5
                    },
                    {
                        'latitude': -70.4836196899414,
                        'point_count': 240,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.5
                    },
                    {
                        'latitude': -71.04524230957031,
                        'point_count': 225,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.600000023841858
                    },
                    {
                        'latitude': -71.60686492919922,
                        'point_count': 225,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.600000023841858
                    },
                    {
                        'latitude': -72.16848754882812,
                        'point_count': 216,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.6666666269302368
                    },
                    {
                        'latitude': -72.73011016845703,
                        'point_count': 216,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.6666666269302368
                    },
                    {
                        'latitude': -73.29173278808594,
                        'point_count': 200,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.7999999523162842
                    },
                    {
                        'latitude': -73.85335540771484,
                        'point_count': 192,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.875
                    },
                    {
                        'latitude': -74.41497802734375,
                        'point_count': 192,
                        'longitude_origin': 0.0,
                        'longitude_step': 1.875
                    },
                    {
                        'latitude': -74.97660064697266,
                        'point_count': 180,
                        'longitude_origin': 0.0,
                        'longitude_step': 2.0
                    },
                    {
                        'latitude': -75.53822326660156,
                        'point_count': 180,
                        'longitude_origin': 0.0,
                        'longitude_step': 2.0
                    },
                    {
                        'latitude': -76.09984588623047,
                        'point_count': 180,
                        'longitude_origin': 0.0,
                        'longitude_step': 2.0
                    },
                    {
                        'latitude': -76.66146850585938,
                        'point_count': 160,
                        'longitude_origin': 0.0,
                        'longitude_step': 2.25
                    },
                    {
                        'latitude': -77.22309112548828,
                        'point_count': 160,
                        'longitude_origin': 0.0,
                        'longitude_step': 2.25
                    },
                    {
                        'latitude': -77.78471374511719,
                        'point_count': 150,
                        'longitude_origin': 0.0,
                        'longitude_step': 2.4000000953674316
                    },
                    {
                        'latitude': -78.3463363647461,
                        'point_count': 144,
                        'longitude_origin': 0.0,
                        'longitude_step': 2.5
                    },
                    {
                        'latitude': -78.907958984375,
                        'point_count': 135,
                        'longitude_origin': 0.0,
                        'longitude_step': 2.6666667461395264
                    },
                    {
                        'latitude': -79.4695816040039,
                        'point_count': 128,
                        'longitude_origin': 0.0,
                        'longitude_step': 2.8125
                    },
                    {
                        'latitude': -80.03120422363281,
                        'point_count': 125,
                        'longitude_origin': 0.0,
                        'longitude_step': 2.880000114440918
                    },
                    {
                        'latitude': -80.59282684326172,
                        'point_count': 120,
                        'longitude_origin': 0.0,
                        'longitude_step': 3.0
                    },
                    {
                        'latitude': -81.15444946289062,
                        'point_count': 120,
                        'longitude_origin': 0.0,
                        'longitude_step': 3.0
                    },
                    {
                        'latitude': -81.71607208251953,
                        'point_count': 108,
                        'longitude_origin': 0.0,
                        'longitude_step': 3.3333332538604736
                    },
                    {
                        'latitude': -82.27769470214844,
                        'point_count': 96,
                        'longitude_origin': 0.0,
                        'longitude_step': 3.75
                    },
                    {
                        'latitude': -82.83931732177734,
                        'point_count': 90,
                        'longitude_origin': 0.0,
                        'longitude_step': 4.0
                    },
                    {
                        'latitude': -83.40093994140625,
                        'point_count': 90,
                        'longitude_origin': 0.0,
                        'longitude_step': 4.0
                    },
                    {
                        'latitude': -83.96255493164062,
                        'point_count': 80,
                        'longitude_origin': 0.0,
                        'longitude_step': 4.5
                    },
                    {
                        'latitude': -84.52417755126953,
                        'point_count': 72,
                        'longitude_origin': 0.0,
                        'longitude_step': 5.0
                    },
                    {
                        'latitude': -85.08580017089844,
                        'point_count': 72,
                        'longitude_origin': 0.0,
                        'longitude_step': 5.0
                    },
                    {
                        'latitude': -85.64742279052734,
                        'point_count': 64,
                        'longitude_origin': 0.0,
                        'longitude_step': 5.625
                    },
                    {
                        'latitude': -86.20904541015625,
                        'point_count': 60,
                        'longitude_origin': 0.0,
                        'longitude_step': 6.0
                    },
                    {
                        'latitude': -86.77066802978516,
                        'point_count': 50,
                        'longitude_origin': 0.0,
                        'longitude_step': 7.199999809265137
                    },
                    {
                        'latitude': -87.33229064941406,
                        'point_count': 45,
                        'longitude_origin': 0.0,
                        'longitude_step': 8.0
                    },
                    {
                        'latitude': -87.89391326904297,
                        'point_count': 40,
                        'longitude_origin': 0.0,
                        'longitude_step': 9.0
                    },
                    {
                        'latitude': -88.45553588867188,
                        'point_count': 36,
                        'longitude_origin': 0.0,
                        'longitude_step': 10.0
                    },
                    {
                        'latitude': -89.01715850830078,
                        'point_count': 25,
                        'longitude_origin': 0.0,
                        'longitude_step': 14.399999618530273
                    },
                    {
                        'latitude': -89.57878112792969,
                        'point_count': 18,
                        'longitude_origin': 0.0,
                        'longitude_step': 20.0
                    }
                ],
                'subset_segments': NULL
            }
        },
    spatial_axes := ['point'],
    include_source := true
);
CREATE TEMP VIEW domain_n160 AS
SELECT * FROM read_om(
    'test/data/grids/gaussian-n160-identity.om',
    dimensions := map(['n160_identity/value'], [[
    'point'
]]),
    domain := 'n160',
    include_source := true
);
CREATE TEMP TABLE baseline_n160 AS SELECT * FROM explicit_n160;
-- Full input was materialized before any restricted query for n160.
SELECT count(*) AS full_rows_n160 FROM explicit_n160;
SELECT count(*) AS materialized_rows_n160 FROM baseline_n160;
SELECT count(*) AS domain_identity_difference_n160 FROM (
    (SELECT om_source.grid_id, om_source.layout_id FROM explicit_n160
     EXCEPT ALL SELECT om_source.grid_id, om_source.layout_id FROM domain_n160)
    UNION ALL
    (SELECT om_source.grid_id, om_source.layout_id FROM domain_n160
     EXCEPT ALL SELECT om_source.grid_id, om_source.layout_id FROM explicit_n160)
);
SELECT count(*) AS restricted_difference_n160 FROM (
    (SELECT * FROM baseline_n160 WHERE latitude BETWEEN -10 AND 10 AND longitude BETWEEN -10 AND 10
     EXCEPT ALL SELECT * FROM explicit_n160 WHERE latitude BETWEEN -10 AND 10 AND longitude BETWEEN -10 AND 10)
    UNION ALL
    (SELECT * FROM explicit_n160 WHERE latitude BETWEEN -10 AND 10 AND longitude BETWEEN -10 AND 10
     EXCEPT ALL SELECT * FROM baseline_n160 WHERE latitude BETWEEN -10 AND 10 AND longitude BETWEEN -10 AND 10)
);
SELECT count(*) AS seam_rows_n160 FROM explicit_n160 WHERE 
    (longitude BETWEEN 170 AND 180 OR longitude BETWEEN -180 AND -170);
SELECT count(*) AS empty_rows_n160 FROM explicit_n160 WHERE latitude > 90;
SELECT count(*) AS fallback_rows_n160 FROM explicit_n160 WHERE abs(latitude) < 1;
SELECT om_source.logical_index, longitude, latitude,
       (longitude BETWEEN -1 AND 1 AND latitude BETWEEN -1 AND 1) AS polygon_covers_point
FROM explicit_n160 -- POLYGON((-1 -1, 1 -1, 1 1, -1 1, -1 -1)), lon/lat order
WHERE longitude BETWEEN -1 AND 1 AND latitude BETWEEN -1 AND 1 LIMIT 64;

-- Pending sample-backed explicit/domain views; no compatible frozen OM v3 input is recorded:
-- NOT RUN n320: keep absent until a matching object and ordered-axis evidence are frozen.
-- NOT RUN n320_ecmwf_aifs_europe_ensemble: keep absent until a matching object and ordered-axis evidence are frozen.
-- In particular, the real ECMWF HRES O1280 sample is not relabelled as N160 or N320.

-- Real ECMWF HRES/IFS OM v3 O1280 value-only supplement; no geographic mapping is asserted.
CREATE TEMP VIEW values_ecmwf_hres_o1280 AS SELECT * FROM read_om('build/s3-samples/openmeteo-v3/ecmwf-ifs-hsurf-o1280.om');
CREATE TEMP TABLE baseline_ecmwf_hres_o1280 AS
    SELECT * FROM values_ecmwf_hres_o1280; -- materialize all 6,599,680 values first
SELECT count(*) AS hres_o1280_value_count FROM values_ecmwf_hres_o1280;

-- Spatial relation result is a smoke query only until the matching producer oracle is available.
