LOAD '/home/blizhan/repo/github/duckomo/build/grid-matrix/baseline-1.5.4/builds/15f751c1929b88adebbfe2a150a8c7987f92de29af7fc0b806a6af1cd80388c8/release/extension/duckomo/duckomo.duckdb_extension';
SET threads=1;
SET duckomo_max_threads=1;
SET duckomo_cache_enabled=true;
SET duckomo_cache_capacity=67108864;

CREATE TEMP TABLE work_small AS SELECT value AS value FROM read_om('/home/blizhan/repo/github/duckomo/test/data/grids/memory-small.om', dimensions := map(['value'], [['latitude_axis','longitude_axis']]), grid := {'version':1,'type':'lambert_conformal_conic','numeric_policy':'float64_v1','earth':{'model':'sphere','radius_m':6371229.0},'layout':{'nx':256,'ny':256,'order':'separate'},'parameters':{'x0':-128000.000000,'y0':-128000.000000,'dx':1000.0,'dy':1000.0,'central_meridian':10.0,'latitude_of_origin':46.244,'standard_parallel_1':40.0,'standard_parallel_2':50.0}}, spatial_axes := ['latitude_axis','longitude_axis']) WHERE latitude BETWEEN 46.243 AND 46.245 AND longitude BETWEEN 9.999 AND 10.001;

COPY (SELECT (SELECT count(*)::UBIGINT FROM work_small) AS result_rows, (SELECT sum(value)::DOUBLE FROM work_small) AS result_sum, (SELECT min(value)::DOUBLE FROM work_small) AS result_min, (SELECT max(value)::DOUBLE FROM work_small) AS result_max, metrics::JSON AS metrics FROM duckomo_last_scan_metrics() ORDER BY scan_id DESC LIMIT 1) TO '/home/blizhan/repo/github/duckomo/specs/004-multi-grid-selection/evidence/baseline-local/h5-local-refresh-20261008-buffer-replacement/us2-local/work-peak-lambert_conformal_conic/small.json' (FORMAT JSON, ARRAY false);

CREATE TEMP TABLE work_large AS SELECT value AS value FROM read_om('/home/blizhan/repo/github/duckomo/test/data/grids/memory-large.om', dimensions := map(['value'], [['latitude_axis','longitude_axis']]), grid := {'version':1,'type':'lambert_conformal_conic','numeric_policy':'float64_v1','earth':{'model':'sphere','radius_m':6371229.0},'layout':{'nx':1024,'ny':1024,'order':'separate'},'parameters':{'x0':-512000.000000,'y0':-512000.000000,'dx':1000.0,'dy':1000.0,'central_meridian':10.0,'latitude_of_origin':46.244,'standard_parallel_1':40.0,'standard_parallel_2':50.0}}, spatial_axes := ['latitude_axis','longitude_axis']) WHERE latitude BETWEEN 46.243 AND 46.245 AND longitude BETWEEN 9.999 AND 10.001;

COPY (SELECT (SELECT count(*)::UBIGINT FROM work_large) AS result_rows, (SELECT sum(value)::DOUBLE FROM work_large) AS result_sum, (SELECT min(value)::DOUBLE FROM work_large) AS result_min, (SELECT max(value)::DOUBLE FROM work_large) AS result_max, metrics::JSON AS metrics FROM duckomo_last_scan_metrics() ORDER BY scan_id DESC LIMIT 1) TO '/home/blizhan/repo/github/duckomo/specs/004-multi-grid-selection/evidence/baseline-local/h5-local-refresh-20261008-buffer-replacement/us2-local/work-peak-lambert_conformal_conic/large.json' (FORMAT JSON, ARRAY false);

