#!/usr/bin/env python3
"""Import independently produced OM grid reference artifacts into frozen manifests.

This command never computes coordinates, row mappings, or decoded values. It
records the exact external command and verifies every declared input/output
SHA-256 so the oracle cannot silently be regenerated by DuckOMO itself.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import re
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
COMMIT_SHA_RE = re.compile(r"^[0-9a-f]{40}$")
REQUIRED_TARGETS = (
    "rotated_v3",
    "lambert_v3",
    "stereographic_v3",
    "gaussian_n160_v3",
    "gaussian_n320_v3",
    "gaussian_n320_region_v3",
)
OUTPUTS = {
    "coordinate": "coordinate-reference.json",
    "region": "region-reference.json",
    "value": "value-reference-manifest.json",
}
METHODS = {
    "coordinate": {"pinned_producer_coordinates", "independent_math"},
    "region": {"producer_grib", "production_archive"},
    "value": {"official_om_c_api"},
}
DEFINITION_TARGETS = {
    "gem_rdps_10km": "rotated_v3",
    "gem_regional": "stereographic_v3",
    "aladin_central_europe_2km": "lambert_v3",
    "n160": "gaussian_n160_v3",
    "n320": "gaussian_n320_v3",
    "n320_ecmwf_aifs_europe_ensemble": "gaussian_n320_region_v3",
}


class ReferenceError(ValueError):
    pass


def load_json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise ReferenceError(f"cannot read JSON object {path}: {error}") from error
    if not isinstance(value, dict):
        raise ReferenceError(f"expected a JSON object in {path}")
    return value


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for block in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def resolve_input(path_value: Any, root: Path, records_dir: Path, field: str) -> tuple[Path, str]:
    if not isinstance(path_value, str) or not path_value:
        raise ReferenceError(f"{field}.path must be a non-empty string")
    path = Path(path_value)
    if not path.is_absolute():
        root_candidate = root / path
        records_candidate = records_dir / path
        path = root_candidate if root_candidate.exists() else records_candidate
    path = path.resolve()
    if not path.is_file():
        raise ReferenceError(f"{field} file does not exist: {path}")
    return path, path_value


def checked_file(record: Any, root: Path, records_dir: Path, field: str) -> dict[str, Any]:
    if not isinstance(record, dict):
        raise ReferenceError(f"{field} must be an object containing path and sha256")
    path, display_path = resolve_input(record.get("path"), root, records_dir, field)
    expected = record.get("sha256")
    if not isinstance(expected, str) or not SHA256_RE.fullmatch(expected):
        raise ReferenceError(f"{field}.sha256 must be a lowercase SHA-256")
    actual = sha256(path)
    if actual != expected:
        raise ReferenceError(f"SHA-256 mismatch for {field} {path}: expected {expected}, got {actual}")
    return {"path": display_path, "sha256": actual, "size_bytes": path.stat().st_size}


def validate_command(value: Any, field: str) -> list[str]:
    if not isinstance(value, list) or not value or any(not isinstance(arg, str) or not arg for arg in value):
        raise ReferenceError(f"{field} must be a non-empty argv array with exact command arguments")
    return value


def validate_records(kind: str, records: Any, root: Path, records_dir: Path,
                     sample_target_by_id: dict[str, str]) -> tuple[list[dict[str, Any]], set[str]]:
    if not isinstance(records, list):
        raise ReferenceError(f"{kind}.references must be an array")
    normalized: list[dict[str, Any]] = []
    targets: set[str] = set()
    for index, record in enumerate(records):
        label = f"{kind}.references[{index}]"
        if not isinstance(record, dict):
            raise ReferenceError(f"{label} must be an object")
        target = record.get("target")
        sample_id = record.get("sample_id")
        method = record.get("method")
        if target not in REQUIRED_TARGETS:
            raise ReferenceError(f"{label}.target must name one of the six frozen required targets")
        if target in targets:
            raise ReferenceError(f"{kind} reference target is repeated: {target}")
        if not isinstance(sample_id, str) or sample_id not in sample_target_by_id:
            raise ReferenceError(f"{label}.sample_id must identify an accepted real OM v3 target sample")
        if sample_target_by_id[sample_id] != target:
            raise ReferenceError(
                f"{label}.sample_id belongs to {sample_target_by_id[sample_id]}, not {target}; "
                "supplemental O/F grids cannot substitute for an N-grid target"
            )
        if method not in METHODS[kind]:
            choices = ", ".join(sorted(METHODS[kind]))
            raise ReferenceError(f"{label}.method must be one of: {choices}")
        command = validate_command(record.get("command"), f"{label}.command")
        inputs = record.get("inputs")
        if not isinstance(inputs, list) or not inputs:
            raise ReferenceError(f"{label}.inputs must list the fixed source/sample inputs and hashes")
        normalized_inputs = [checked_file(item, root, records_dir, f"{label}.inputs[{n}]")
                             for n, item in enumerate(inputs)]
        artifact = checked_file(record.get("artifact"), root, records_dir, f"{label}.artifact")
        row_count = record.get("row_count")
        if not isinstance(row_count, int) or isinstance(row_count, bool) or row_count <= 0:
            raise ReferenceError(f"{label}.row_count must be a positive integer")
        result: dict[str, Any] = {
            "target": target,
            "sample_id": sample_id,
            "method": method,
            "command": command,
            "inputs": normalized_inputs,
            "artifact": artifact,
            "row_count": row_count,
        }
        if kind == "coordinate":
            tolerance = record.get("tolerance_degrees")
            policy = record.get("numeric_policy")
            maximum = {"openmeteo_f32_v1": 1e-4, "float64_v1": 1e-8}.get(policy)
            if not isinstance(tolerance, (int, float)) or isinstance(tolerance, bool) or \
                    not math.isfinite(tolerance) or tolerance <= 0 or maximum is None or tolerance > maximum:
                raise ReferenceError(f"{label} tolerance exceeds the frozen numeric-policy limit")
            result["numeric_policy"] = policy
            result["tolerance_degrees"] = tolerance
        if kind == "region":
            required_fields = ("source_grid_id", "parent_grid_id", "position_columns")
            if any(not isinstance(record.get(field), str) or not record[field] for field in required_fields):
                raise ReferenceError(f"{label} must include source_grid_id, parent_grid_id, and position_columns")
            result.update({field: record[field] for field in required_fields})
        if kind == "value":
            if not isinstance(record.get("variable_path"), str) or not record["variable_path"]:
                raise ReferenceError(f"{label}.variable_path must identify the decoded OM variable")
            library_commit = record.get("official_library_commit")
            if not isinstance(library_commit, str) or not COMMIT_SHA_RE.fullmatch(library_commit):
                raise ReferenceError(f"{label}.official_library_commit must be a full 40-character commit")
            null_count = record.get("null_count")
            if not isinstance(null_count, int) or isinstance(null_count, bool) or null_count < 0:
                raise ReferenceError(f"{label}.null_count must report the official decode null count")
            result["variable_path"] = record["variable_path"]
            result["official_library_commit"] = library_commit
            result["null_count"] = null_count
        normalized.append(result)
        targets.add(target)
    normalized.sort(key=lambda entry: entry["target"])
    return normalized, targets


def output_document(kind: str, records: list[dict[str, Any]], found: set[str]) -> dict[str, Any]:
    missing = sorted(set(REQUIRED_TARGETS) - found)
    document: dict[str, Any] = {
        "schema_version": 1,
        "reference_kind": kind,
        "status": "complete_imported" if not missing else "partial_not_run",
        "required_targets": list(REQUIRED_TARGETS),
        "covered_targets": sorted(found),
        "missing_targets": missing,
        "references": records,
    }
    if kind == "coordinate":
        document["maximum_allowed_tolerance_degrees"] = {
            "openmeteo_f32_v1": 1e-4,
            "float64_v1": 1e-8,
        }
        document["tolerances_within_limit"] = all(
            entry["tolerance_degrees"] <= document["maximum_allowed_tolerance_degrees"][entry["numeric_policy"]]
            for entry in records
        )
    return document


def iter_sample_objects(document: Any) -> list[dict[str, Any]]:
    found: list[dict[str, Any]] = []
    if isinstance(document, dict):
        if isinstance(document.get("id"), str) and "grid_definition_id" in document and \
                "classification" in document and "format_version" in document:
            found.append(document)
        for value in document.values():
            found.extend(iter_sample_objects(value))
    elif isinstance(document, list):
        for value in document:
            found.extend(iter_sample_objects(value))
    return found


def accepted_sample_targets(objects: list[Any]) -> dict[str, str]:
    return {
        item["id"]: DEFINITION_TARGETS[item["grid_definition_id"]]
        for item in objects
        if isinstance(item, dict) and isinstance(item.get("classification"), str) and
        item["classification"].startswith("real_") and item["classification"].endswith("_om_v3") and
        item.get("format_version") == 3 and isinstance(item.get("id"), str) and
        item.get("grid_definition_id") in DEFINITION_TARGETS
    }


def generate(args: argparse.Namespace) -> list[Path]:
    root = args.root.resolve()
    sample_manifest_path = args.sample_manifest.resolve()
    records_path = args.records.resolve()
    samples = load_json(sample_manifest_path)
    objects = samples.get("public_open_meteo_samples", {}).get("objects", [])
    if not isinstance(objects, list):
        raise ReferenceError("sample manifest public_open_meteo_samples.objects must be an array")
    sample_target_by_id = accepted_sample_targets(iter_sample_objects(samples))

    evidence = load_json(records_path)
    if evidence.get("schema_version") != 1:
        raise ReferenceError("reference import file must use schema_version=1")
    output_paths = {kind: args.output_dir / filename for kind, filename in OUTPUTS.items()}
    existing = [path for path in output_paths.values() if path.exists()]
    if existing and not args.force:
        raise ReferenceError(
            "refusing to overwrite existing reference manifests without --force: " +
            ", ".join(str(path) for path in existing)
        )

    documents: dict[str, dict[str, Any]] = {}
    for kind in OUTPUTS:
        records, found = validate_records(kind, evidence.get(kind, {}).get("references", []),
                                          root, records_path.parent, sample_target_by_id)
        document = output_document(kind, records, found)
        output = output_paths[kind]
        if kind == "value" and output.exists():
            previous = load_json(output)
            previous_supplemental = previous.get("supplemental_references", previous.get("samples"))
            if isinstance(previous_supplemental, list):
                document["supplemental_references"] = previous_supplemental
                document["supplemental_scope"] = previous.get(
                    "supplemental_scope", previous.get("scope", "existing supplemental value evidence")
                )
            previous_gates = previous.get("required_target_gates", {})
            legacy_gate_key = {
                "rotated_v3": "rotated",
                "lambert_v3": "lambert",
                "stereographic_v3": "stereographic",
                "gaussian_n160_v3": "gaussian_n160",
                "gaussian_n320_v3": "gaussian_n320",
                "gaussian_n320_region_v3": "gaussian_n320_region",
            }
            document["required_target_gates"] = {
                target: ("official reference imported; DuckOMO comparison not-run" if target in found else
                         previous_gates.get(target, previous_gates.get(legacy_gate_key[target],
                                            "not-run; required independent reference missing"))
                         )
                for target in REQUIRED_TARGETS
            }
            for key in ("supplemental_out_of_scope", "source_manifest"):
                if key in previous:
                    document[key] = previous[key]
        documents[kind] = document

    written_outputs: list[Path] = []
    for kind in OUTPUTS:
        output = output_paths[kind]
        document = documents[kind]
        output.parent.mkdir(parents=True, exist_ok=True)
        temporary = output.with_name(output.name + ".tmp")
        temporary.write_text(json.dumps(document, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        temporary.replace(output)
        written_outputs.append(output)
    return written_outputs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--sample-manifest", type=Path,
                        default=ROOT / "test/data/grids/sample-manifest.json")
    parser.add_argument("--records", type=Path, required=True,
                        help="JSON with independently produced coordinate/region/value artifact records")
    parser.add_argument("--output-dir", type=Path, default=ROOT / "test/data/grids")
    parser.add_argument("--force", action="store_true", help="replace existing reference manifests")
    args = parser.parse_args()
    try:
        outputs = generate(args)
    except (OSError, json.JSONDecodeError, ReferenceError, TypeError, AttributeError) as error:
        print(f"grid reference import failed: {error}", file=sys.stderr)
        return 1
    for output in outputs:
        print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
